name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  FRONTEND_REPOSITORY: wpoms-abhinav-frontend
  BACKEND_REPOSITORY: wpoms-abhinav-backend
  S3_BUCKET: wpoms-abhinav-deploy-files

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Tag
        id: tag
        run: |
          TAG=${GITHUB_SHA::7}-$(date +%s)
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Frontend
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.image_tag }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}

          docker build -t $FRONTEND_REPOSITORY:$IMAGE_TAG ./wpoms_web
          docker tag $FRONTEND_REPOSITORY:$IMAGE_TAG $REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG

      - name: Build & Push Backend
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.image_tag }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}

          docker build -t $BACKEND_REPOSITORY:$IMAGE_TAG ./wpoms_admin
          docker tag $BACKEND_REPOSITORY:$IMAGE_TAG $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG

      - name: Upload docker-compose to S3
        run: |
          aws s3 cp docker-compose.yml s3://$S3_BUCKET/docker-compose.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "Starting deployment..."

            export AWS_REGION=${{ secrets.AWS_REGION }}
            export IMAGE_TAG=${{ needs.build.outputs.image_tag }}

            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            export ECR_REGISTRY="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

            export FRONTEND_REPOSITORY=wpoms-abhinav-frontend
            export BACKEND_REPOSITORY=wpoms-abhinav-backend
            export S3_BUCKET=wpoms-abhinav-deploy-files

            mkdir -p ~/app
            cd ~/app

            aws s3 cp s3://$S3_BUCKET/docker-compose.yml docker-compose.yml

            export POSTGRES_DB=$(aws ssm get-parameter \
              --name "/wpoms/POSTGRES_DB" \
              --query "Parameter.Value" \
              --output text)

            export POSTGRES_USER=$(aws ssm get-parameter \
              --name "/wpoms/POSTGRES_USER" \
              --query "Parameter.Value" \
              --output text)

            export POSTGRES_PASSWORD=$(aws ssm get-parameter \
              --name "/wpoms/POSTGRES_PASSWORD" \
              --with-decryption \
              --query "Parameter.Value" \
              --output text)

            aws ecr get-login-password --region $AWS_REGION | \
              docker login --username AWS --password-stdin $ECR_REGISTRY

            docker compose down || true
            docker compose pull
            docker compose up -d

            echo "Verifying services are healthy..."
            [ "$(curl -s -o /dev/null -w "%{http_code}" --retry 15 --retry-connrefused --retry-delay 2 http://localhost:5173)" = "200" ]
            [ "$(curl -s -o /dev/null -w "%{http_code}" --retry 15 --retry-connrefused --retry-delay 2 http://localhost:8081/actuator/health)" = "200" ]

            echo "Deployment successful and verified"

      